export interface ProductsResponse {
    IDPRODUCTO?:     number;
    DESCRIPCION:    string;
    PRECIO_COMPRA:  number;
    PRECIO:         number;
    FOTO?:           null;
    STOCK:          number;
    ESTADOPRODUCTO: Estadoproducto;
}

export enum Estadoproducto {
    Activo = "activo",
    ESTADOPRODUCTOActivo = "Activo",
}


// Generated by https://quicktype.io
export interface DeleteProductResponse {
    code: number;
    data: Data;
}

export interface Data {
    msg:    string;
    result: Result;
}

export interface Result {
    fieldCount:   number;
    affectedRows: number;
    insertId:     number;
    serverStatus: number;
    warningCount: number;
    message:      string;
    protocol41:   boolean;
    changedRows:  number;
}
